// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUXUYYDa78WkIWz4NAiUxKpyvHWFRTlJo',
    appId: '1:891586164230:android:47221805f19f936bcdf587',
    messagingSenderId: '891586164230',
    projectId: 'flutter-video-audio-chat-d15db',
    storageBucket: 'flutter-video-audio-chat-d15db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yz6h78hmr6N57Qgss7hOZBiFDRWHWac',
    appId: '1:891586164230:ios:33b4a6fc75e3c80ccdf587',
    messagingSenderId: '891586164230',
    projectId: 'flutter-video-audio-chat-d15db',
    storageBucket: 'flutter-video-audio-chat-d15db.appspot.com',
    androidClientId: '891586164230-pvg461rt57tg1f0mootdm5gjqb3tkp2d.apps.googleusercontent.com',
    iosClientId: '891586164230-aj6bgmaga81i4mrpf96r9ueros08fi1m.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.chatty',
  );
}
